# Generated by Django 4.0.4 on 2022-05-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_movies', '0011_remove_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='movie',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, to='my_movies.movie'),
        ),
    ]
