# Generated by Django 4.0.4 on 2022-06-02 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_movies', '0013_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fan',
            field=models.ManyToManyField(related_name='fan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='review',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
